import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
        <ul className="navigation">
          <li><Link href="/signup">Sign Up</Link></li>
          <li><Link href="/registration">Login</Link></li>
          <li><Link href="/">Home</Link></li>
          <li><Link href="/dynamicroute/userlist/1">User 1</Link></li>
          <li><Link href="/dynamicroute/userlist/2">User 2</Link></li>
          <li><Link href="/route/about">About</Link></li>
          <li><Link href="/route/contact">Contact</Link></li>
        </ul>
      </body>
    </html>
  );
}
